name: Compile Sketches

# If any permissions specified, all other permissions
# default to 'none' (except metadata == read)
permissions:
  contents:             none

# Controls when the workflow will run
on:
  # Triggers the workflow on push requests
  push:
    # but exclude dependabot branches (will be done in pull request)
    branches:
      - '**'
      - '!**-dev'
      - '!dev/**'
      - '!dependabot/**'

  # Trigger the workflow on pull requests
  pull_request:
    # but exclude PRs that target a dependabot branch
    branches:
      - '**'
      - '!**-dev'
      - '!dev/**'
      - '!dependabot/**'

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:


env:
  SKETCHES_REPORTS_PATH: reports
  # Do not change the artifact name ... it's used in report_deltas action also...

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          # MegaCoreX is an Arduino-compatible alternative that some prefer for MegaAVR boards
          - fqbn: MegaCoreX:megaavr:4809:pinout=48pin_standard,eeprom=erase,resetpin=reset,BOD=disabled,clock=internal_16MHz,bootloader=no_bootloader
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: MegaCoreX_megaavr_4809

          # # ATTinyCore BSP v2.x ...
          # # - ATTinyCore:avr:attinyx5:chip=85,clock=internal_8m,eesave=disable,softserial=txonly,bod=disable,millis=enabled
          # #   ARTIFACT_SUFFIX: ATTinyCore_BSP_v2

          # ATTinyCore BSP v1.x ...
          # Amazing!  Arduino-compatible support for ATTiny chips!
          - fqbn: ATTinyCore:avr:attinyx5:chip=85,LTO=enable,clock=8internal,eesave=disable,bod=disable,millis=enabled
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: ATTinyCore_avr_attinyx5

          # Arduino AVR Boards
          - fqbn: arduino:avr:uno                  # Arduino Uno
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino_avr_uno
          - fqbn: arduino:avr:nano                 # Arduino Nano
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__avr__nano

          # Arduino MegaAVR Boards
          - fqbn: arduino:megaavr:uno2018          # Arduino Uno WiFi Rev2
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__megaavr__uno2018
          - fqbn: arduino:megaavr:nona4809         # Arduino Nano Every
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__megaavr__nona4809

          # Arduino SAM Boards
          - fqbn: arduino:sam:arduino_due_x_dbg    # Arduino Due (Programming Port)
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__sam__arduino_due

          # Arduino SAMD Boards
          - fqbn: arduino:samd:mkrzero             # Arduino MKRZERO
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino_samd_mkrzero
          - fqbn: arduino:samd:nano_33_iot         # Arduino NANO 33 IoT
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__samd__nano_33_iot

          # ESP8266 - Community-driven BSP support
          - fqbn: esp8266:esp8266:generic              # Generic ESP8266 Module
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__esp8266__generic
          - fqbn: esp8266:esp8266:esp8285              # Generic ESP8285 Module
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__esp8266__esp8285
          - fqbn: esp8266:esp8266:espduino             # ESPDuino (ESP-13 Module)
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__esp8266__espduino
          - fqbn: esp8266:esp8266:espino               # ESPino (ESP-12 Module)
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__esp8266__espino
          - fqbn: esp8266:esp8266:d1_mini              # LOLIN(WEMOS) D1 R2 & mini
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__esp8266__d1_mini

          # Espressif ESP32 BSP
          - fqbn: esp32:esp32:esp32                    # ESP32 Dev Module
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__esp32__esp32
          - fqbn: esp32:esp32:esp32c3                  # ESP32C3 Dev Module
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__esp32__esp32c3
          - fqbn: esp32:esp32:esp32s2                  # ESP32S2 Dev Module
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__esp32__esp32s2
          - fqbn: esp32:esp32:esp32s3                  # ESP32S3 Dev Module
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__esp32__esp32s3

          # Arduino MBED-based devices
          - fqbn: arduino:mbed_edge:edge_control       # Arduino Edge Control
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__mbed_edge__edge_control
          - fqbn: arduino:mbed_nano:nano33ble          # Arduino Nano 33 BLE
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__mbed_nano__nano33ble
          - fqbn: arduino:mbed_nano:nanorp2040connect  # Arduino Nano RP2040 Connect
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__mbed_nano__nanorp2040connect
          - fqbn: arduino:mbed_portenta:envie_m7       # Arduino Portenta H7 (M7 core)
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__mbed_portenta__envie_m7
          - fqbn: arduino:mbed_rp2040:pico             # Raspberry Pi Pico
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__mbed_rp2040__pico
          - fqbn: arduino:mbed_nicla:nicla_sense       # Nicla Sense ME
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__mbed_nicla__nicla_sense
          - fqbn: arduino:mbed_nicla:nicla_vision      # Nicla Vision
            SKETCHES_REPORTS_ARTIFACT_SUFFIX: arduino__mbed_nicla__nicla_vision

            # # The following boards are explicitly NOT supported:
            # # Arduino Portenta X8 -- Requires custom library SerialRPC to use serial
            # # Arduino PRIMO       -- Compiler does not support C++11


    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-telemetry: true # disables telemetry sent to StepSecurity when egress policy is set to 'block'
          allowed-endpoints: >
            MCUdude.github.io:443
            SpenceKonde.github.io:443
            arduino.esp8266.com:80
            azduino.com:443
            azure.archive.ubuntu.com:80
            downloads.arduino.cc:443
            downloads.arduino.cc:80
            drazzy.com:80
            files.pythonhosted.org:443
            github.com:443
            launchpad.net:443
            mcudude.github.io:443
            objects.githubusercontent.com:443
            packages.microsoft.com:443
            pipelines.actions.githubusercontent.com:443
            ppa.launchpad.net:80
            pypi.org:443
            raw.githubusercontent.com:443

      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      
      - name: Compile
        uses: arduino/compile-sketches@8fd840319c8c9b8617a42cc731092a3350599f35
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: |
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:avr
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:megaavr
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:sam
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:samd
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:mbed_edge
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:mbed_nano
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:mbed_portenta
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:mbed_rp2040
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:mbed_nicla
            - source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
              name: esp8266:esp8266
            - source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
              name: esp32:esp32
            - source-url: http://drazzy.com/package_drazzy.com_index.json
              name: ATTinyCore:avr
            - source-url: https://mcudude.github.io/MegaCoreX/package_MCUdude_MegaCoreX_index.json
              name: MegaCoreX:megaavr

          # will automatically find sketches in subdirectories
          sketch-paths: examples
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          cli-version: latest
          enable-deltas-report: true
          enable-warnings-report: true

      - name: Upload sketches report as workflow artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          if-no-files-found: error
          name: sketches-report--${{ matrix.board.SKETCHES_REPORTS_ARTIFACT_SUFFIX }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
