name: Compile Sketches

# If any permissions specified, all other permissions
# default to 'none' (except metadata == read)
permissions:
  contents:             none

# Controls when the workflow will run
on:
  # Triggers the workflow on push requests
  push:
    # but exclude dependabot branches (will be done in pull request)
    branches:
      - '**'
      - '!dependabot/**'

  # Trigger the workflow on pull requests
  pull_request:
    # but exclude PRs that target a dependabot branch
    branches:
      - '**'
      - '!dependabot/**'

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:


env:
  SKETCHES_REPORTS_PATH: reports
  # Do not change the artifact name ... it's used in report_deltas action also...
  SKETCHES_REPORTS_ARTIFACT_NAME: sketches-reports

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fqbn:

          # MegaCoreX is an Arduino-compatible alternative that some prefer for MegaAVR boards
          - MegaCoreX:megaavr:4809:pinout=48pin_standard,eeprom=erase,resetpin=reset,BOD=disabled,clock=internal_16MHz,bootloader=no_bootloader

          # # ATTinyCore BSP v2.x ...
          # # - ATTinyCore:avr:attinyx5:chip=85,clock=internal_8m,eesave=disable,softserial=txonly,bod=disable,millis=enabled

          # ATTinyCore BSP v1.x ...
          # Amazing!  Arduino-compatible support for ATTiny chips!
          - ATTinyCore:avr:attinyx5:chip=85,LTO=enable,clock=8internal,eesave=disable,bod=disable,millis=enabled

          # Arduino AVR Boards
          - arduino:avr:uno                  # Arduino Uno
          - arduino:avr:nano                 # Arduino Nano

          # Arduino MegaAVR Boards
          - arduino:megaavr:uno2018          # Arduino Uno WiFi Rev2
          - arduino:megaavr:nona4809         # Arduino Nano Every

          # Arduino SAM Boards
          - arduino:sam:arduino_due_x_dbg    # Arduino Due (Programming Port)

          # Arduino SAMD Boards
          - arduino:samd:mkrzero             # Arduino MKRZERO
          - arduino:samd:nano_33_iot         # Arduino NANO 33 IoT

          # ESP8266 - Community-driven BSP support
          - esp8266:esp8266:generic              # Generic ESP8266 Module
          - esp8266:esp8266:esp8285              # Generic ESP8285 Module
          - esp8266:esp8266:espduino             # ESPDuino (ESP-13 Module)
          - esp8266:esp8266:espino               # ESPino (ESP-12 Module)
          - esp8266:esp8266:d1_mini              # LOLIN(WEMOS) D1 R2 & mini

          # Espressif ESP32 BSP
          - esp32:esp32:esp32                    # ESP32 Dev Module
          - esp32:esp32:esp32c3                  # ESP32C3 Dev Module
          - esp32:esp32:esp32s2                  # ESP32S2 Dev Module
          - esp32:esp32:esp32s3                  # ESP32S3 Dev Module

          # Arduino MBED-based devices
          - arduino:mbed_edge:edge_control       # Arduino Edge Control
          - arduino:mbed_nano:nano33ble          # Arduino Nano 33 BLE
          - arduino:mbed_nano:nanorp2040connect  # Arduino Nano RP2040 Connect
          - arduino:mbed_portenta:envie_m7       # Arduino Portenta H7 (M7 core)
          - arduino:mbed_portenta:envie_m4       # Arduino Portenta H7 (M4 core)
          - arduino:mbed_rp2040:pico             # Raspberry Pi Pico
          - arduino:mbed_nicla:nicla_sense       # Nicla Sense ME
          - arduino:mbed_nicla:nicla_vision      # Nicla Vision

          # # The following boards are explicitly NOT supported:
          # # Arduino Portenta X8 -- Requires custom library SerialRPC to use serial
          # # Arduino PRIMO -- Compiler does not support C++11


    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-telemetry: true # disables telemetry sent to StepSecurity when egress policy is set to 'block'
          allowed-endpoints: >
            MCUdude.github.io:443
            SpenceKonde.github.io:443
            arduino.esp8266.com:80
            azduino.com:443
            azure.archive.ubuntu.com:80
            downloads.arduino.cc:443
            downloads.arduino.cc:80
            drazzy.com:80
            files.pythonhosted.org:443
            github.com:443
            launchpad.net:443
            mcudude.github.io:443
            objects.githubusercontent.com:443
            packages.microsoft.com:443
            pipelines.actions.githubusercontent.com:443
            ppa.launchpad.net:80
            pypi.org:443
            raw.githubusercontent.com:443

      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      
      - name: Compile
        uses: arduino/compile-sketches@1edb1fde2dd10524d345c853e888f487459667aa
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:avr
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:megaavr
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:sam
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:samd
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:mbed_edge
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:mbed_nano
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:mbed_portenta
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:mbed_rp2040
            - source-url: https://downloads.arduino.cc/packages/package_index.json
              name: arduino:mbed_nicla
            - source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
              name: esp8266:esp8266
            - source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
              name: esp32:esp32
            - source-url: http://drazzy.com/package_drazzy.com_index.json
              name: ATTinyCore:avr
            - source-url: https://mcudude.github.io/MegaCoreX/package_MCUdude_MegaCoreX_index.json
              name: MegaCoreX:megaavr

          # will automatically find sketches in subdirectories
          sketch-paths: examples
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          cli-version: latest
          enable-deltas-report: true
          enable-warnings-report: true

      - name: Upload sketches report as workflow artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
