name: Report size deltas

on:
  workflow_dispatch:
  schedule:
    # Example was to run every 5 minutes
    # Running every 20 minutes is "fast enough"
    - cron:  '*/20 * * * *'

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: report size deltas
        uses: arduino/report-size-deltas@a4d949978b5bb0c2c3fe6147b345d5bb8fa3f4fe
